# import tkinter as tk
#
# window = tk.Tk()
# window.title('Калькулятор')
# window.geometry("350x350")
# window.resizable(False, False)
# button_add = tk.Button(window, text="+", width=2, height=2, command=add)
# button_add.place(x=100, y=200)
# button_sub = tk.Button(window, text="-", width=2, height=2, command=sub)
# button_sub.place(x=150, y=200)
# button_mul = tk.Button(window, text="*", width=2, height=2, command=mul)
# button_mul.place(x=200, y=200)
# button_div = tk.Button(window, text="/", width=2, height=2, command=div)
# button_div.place(x=250, y=200)
# number1_entry = tk.Entry(window, width=28)
# number1_entry.place(x=100, y=75)
# number2_entry = tk.Entry(window, width=28)
# number2_entry.place(x=100, y=150)
# answer_entry = tk.Entry(window, width=28)
# answer_entry.place(x=100, y=300)
# number1 = tk.Label(window, text="Введите первое число:")
# number1.place(x=100, y=50)
# number2 = tk.Label(window, text="Введите второе число:")
# number2.place(x=100, y=125)
# answer = tk.Label(window, text="Ответ:")
# answer.place(x=100, y=275)
# window.mainloop()

import tkinter as tk

window = tk.Tk()
window.title('Калькулятор')
window.geometry("350x350")
window.resizable(False, False)
button_add = tk.Button(window, text="+", width=2, height=2, command=add)
button_add.place(x=100, y=200)
button_sub = tk.Button(window, text="-", width=2, height=2, command=sub)
button_sub.place(x=150, y=200)
button_mul = tk.Button(window, text="*", width=2, height=2, command=mul)
button_mul.place(x=200, y=200)
button_div = tk.Button(window, text="/", width=2, height=2, command=div)
button_div.place(x=250, y=200)
number1_entry = tk.Entry(window, width=28)
number1_entry.place(x=100, y=75)
number2_entry = tk.Entry(window, width=28)
number2_entry.place(x=100, y=150)
answer_entry = tk.Entry(window, width=28)
answer_entry.place(x=100, y=300)
number1 = tk.Label(window, text="Введите первое число:")
number1.place(x=100, y=50)
number2 = tk.Label(window, text="Введите второе число:")
number2.place(x=100, y=125)
answer = tk.Label(window, text="Ответ:")
answer.place(x=100, y=275)
window.mainloop()